/**
 * Read and parse Composer's installed.json to iterate over installed packages.
 *
 * Magento 2 relies heavily on Composer for module/theme/library management.
 * The installed.json file, generated by Composer, contains metadata about every
 * installed package including its type, install path, and autoload configuration.
 *
 * This module provides a single entry point for iterating over these packages,
 * eliminating the need for each consumer (moduleResolver, composerAutoload,
 * themeResolver) to independently read, parse, and handle the Composer v1/v2
 * format differences.
 *
 * Composer v1: installed.json is a top-level JSON array of package objects.
 * Composer v2: installed.json is an object with a "packages" key containing the array.
 */

import * as fs from 'fs';
import * as path from 'path';
import { realpath } from './realpath';

/**
 * A single Composer package with its resolved absolute install path.
 *
 * The `raw` field provides access to the full package JSON for type-specific
 * fields (e.g., autoload.psr-4, autoload.files) without forcing a shared type.
 */
export interface ComposerPackage {
  /** Absolute filesystem path to the package root (symlinks resolved). */
  absPath: string;
  /** The package type as declared in composer.json (e.g., "magento2-module", "magento2-theme"). */
  type: string | undefined;
  /** The raw package object from installed.json, for accessing any additional fields. */
  raw: Record<string, unknown>;
}

/**
 * Read vendor/composer/installed.json and yield each package with its resolved path.
 *
 * Handles both Composer v1 (top-level array) and v2 (object with "packages" key).
 * The install-path field is relative to vendor/composer/ — this function resolves
 * it to an absolute path with symlinks resolved for consistency with the rest of
 * the LSP's path handling.
 *
 * Returns an empty array if installed.json is missing, unreadable, or malformed.
 */
export function readComposerPackages(magentoRoot: string): ComposerPackage[] {
  const installedJsonPath = path.join(
    magentoRoot,
    'vendor',
    'composer',
    'installed.json',
  );

  try {
    const content = fs.readFileSync(installedJsonPath, 'utf-8');
    const data = JSON.parse(content);
    // Composer v2 wraps packages in a "packages" key; v1 is a plain array
    const packages: Record<string, unknown>[] = data.packages ?? data;

    const result: ComposerPackage[] = [];
    for (const pkg of packages) {
      const installPath = pkg['install-path'];
      if (typeof installPath !== 'string' || !installPath) continue;

      // install-path is relative to vendor/composer/ — resolve to absolute
      const absPath = realpath(
        path.resolve(magentoRoot, 'vendor', 'composer', installPath),
      );

      result.push({
        absPath,
        type: typeof pkg.type === 'string' ? pkg.type : undefined,
        raw: pkg,
      });
    }
    return result;
  } catch {
    // installed.json not found, unreadable, or malformed JSON
    return [];
  }
}
